version: '3.4'

services:
  meliora:
    container_name: meliorablazor
    image: ${DOCKER_REGISTRY-}meliora
    build:
      context: .
      dockerfile: Meliora/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest # Use the desired SQL Server version
    container_name: sqlserverdb
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql # Persistent SQL Server data
      - ./sql:/var/opt/sqlscripts # Mount the directory containing init.sql
    ports:
      - "1433:1433" # Default SQL Server port
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -d master -i /var/opt/sqlscripts/init.sql
        wait

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Interface web do MailHog
      - "1025:1025" # SMTP server

volumes:
  sql_data:
    driver: local
  data_protection_keys:
    driver: local
