version: '3.4'

services:
  meliora:
    container_name: meliorablazor
    image: ${DOCKER_REGISTRY-}meliora
    build:
      context: .
      dockerfile: Meliora/Dockerfile

  db:
    image: postgres:16.2
    container_name: postgresdb
    network_mode: host
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=runiversity
      - POSTGRES_USER=runiversity
      - POSTGRES_DB=runiversity
    volumes:
#      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
#      - ./sql/criartransacao.sql:/docker-entrypoint-initdb.d/11-criartransacao.sql:ro
#      - ./sql/resetdb.sql:/docker-entrypoint-initdb.d/21-resetdb.sql:ro
      - type: tmpfs
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "runiversity"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Interface web do MailHog
      - "1025:1025" # SMTP server